name: Production deployment

on:
  release: # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=unpublished#release
    types:
      - unpublished # A release or pre-release was unpublished.
      - released # A release was published, or a pre-release was changed to a release.

jobs:
  version:
    name: Calculate version to deploy
    runs-on: 'ubuntu-latest'
    environment: 'Production'
    outputs:
      tag: ${{ steps.tag.output.tag }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Find latest release
        id: tag
        run: |
          TAG=$(gh release list --repo ${{ github.repository }} --json tagName,isLatest -q 'map(select(.isLatest == true)).[0].tagName')
          echo "tag=$TAG" >> "$GITHUB_OUTPUT"
  check:
    name: Check if the tag is right
    runs-on: 'ubuntu-latest'
    environment: 'Production'
    needs: version
    steps:
      - name: Print tag
        run: echo "${{ needs.version.outputs.tag}}"
