name: Production deployment

on: release

jobs:
  version:
    name: Calculate version to deploy
    runs-on: 'ubuntu-latest'
    environment: 'Production'
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - name: Find latest release
        id: tag
        run: |
          TAG=$(gh release list --repo ${{ github.repository }} --json tagName,isLatest -q 'map(select(.isLatest == true)).[0].tagName')
          echo "tag=$TAG"
          echo "tag=$TAG" >> $GITHUB_OUTPUT
  check:
    name: Check if the tag is right
    runs-on: 'ubuntu-latest'
    environment: 'Production'
    needs: version
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.version.outputs.tag}}
      - name: Print tag
        run: echo "${{ needs.version.outputs.tag}}"
